name: Build - Lint - Test

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm test ${{ contains(matrix.node-version, '18.x') && ' -- --coverage' || '' }}
        env:
          CI: true
      - uses: codecov/codecov-action@v1
        name: Upload coverage to Codecov
        if: contains(matrix.node-version, '18.x')
